"""
Django settings for BarberS project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os

from zeep import Client

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lv1yan%7)yh6b5sm5_%jt17i)uicb4*@za3bf2f&m!n0+d(^%c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',

    'client.apps.ClientConfig',
    'barber.apps.BarberConfig',
]
# Application definition


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BarberS.urls'

WSGI_APPLICATION = 'BarberS.wsgi.application'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'barber_s',
        'USER': 'barber',
        'PASSWORD': 'barberer',
        'HOST': 'localhost',
        'PORT': '5432',
        'CONN_MAX_AGE': None,
    }
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',)
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# DJ
# APPEND_SLASH = False
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = 'media/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'

LOCATION_SEPARATOR = ' -- '

MAX_RESERVE_LIMIT = 1

SERVER_BASE_URL = 'http://5.253.24.199:8000/'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


error_status = {
    'server_error': {
        'code': 199,
        'message': 'مشکل ناشناخته‌ای در پردازش درخواست پیش آمد'
    },
    'auth_failure': {
        'code': 121,
        'message': 'ورود به مشکل برخورد'
    },
    'auth_no_code_found': {
        'code': 103,
        'message': 'کد مورد نظر یافت نشد'
    },
    'auth_wrong_code': {
        'code': 101,
        'message': 'کد اشتباه وارد شده'
    },
    'wrong_parameters': {
        'code': 804,
        'message': 'پارامتر‌های ارسالی اشتباه است'
    },
    'no_data_found': {
        'code': 802,
        'message': 'داده‌ی مربوط یافت نشد'
    },
    'access_denied': {
        'code': 1006,
        'message': 'شما دسترسی به این عملیات را ندارید'
    },
    'no_location_found': {
        'code': 311,
        'message': 'موقعیت مکانی ثبت نشده'
    },
    'not_allowed_action': {
        'code': 1001,
        'message': 'این درخواست قابل قبول نیست'
    }
}


def generate_image_url(obj):
    return obj.image.storage.base_url + obj.image.storage.base_location + obj.image.url
#
# import dj_database_url
#
# prod_db = dj_database_url.config(conn_max_age=500)
# DATABASES['default'].update(prod_db)
#
